# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'meetmode' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for meetmode
  pod 'Mapbox-iOS-SDK', '~> 5.5'
  pod 'SnapKit', '~> 4.0.0'
  pod 'MapboxNavigation', '~> 0.38'
  pod 'UberRides', '~> 0.12'
  pod 'RIBs'
  pod 'RxSwift'
  pod 'RxGesture'
  pod 'RxDataSources'
  pod 'SwiftLocation'
  pod 'EFCountingLabel'
  pod 'LyftSDK'
end
